---
- name: Exercise2
  hosts: arista
  gather_facts: false

  tasks:
    - name: Get ARP Table
      arista.eos.eos_command:
        commands: show ip arp
      register: output

    - ansible.builtin.debug:
        var: output.stdout[0]

    - ansible.builtin.set_fact:
        arpTable: "{{ output.stdout[0] }}"

    - ansible.builtin.debug:
        var: arpTable

    - name: Filter ARP Table
      ansible.builtin.debug:
        msg: "{{ arpTable | parseARP }}"
