---
- name: Exercise3b
  hosts: arista
  gather_facts: false

  vars:
    platform: "arista_eos"
    command: "show vlan"
    textfsm_rel_path: "ntc-templates/ntc_templates/templates/"

  tasks:
    - name: Get VLANs
      arista.eos.eos_command:
        commands: "{{ command }}"
      register: output

    - ansible.builtin.debug:
        msg: "{{ output }}"

    # This is only needed so our automated tests work properly
    - name: "Set home directory as ntc_parse doesn't understand ~"
      ansible.builtin.set_fact:
        textfsm_index: "{{ inventory_dir }}/{{textfsm_rel_path }}"

    - ansible.builtin.set_fact:
        parsed_vlans: "{{ output.stdout[0] | ntc_parse(command, platform, textfsm_index) }}"

    - ansible.builtin.debug:
        var: parsed_vlans
