---
- name: Exercise 3
  hosts: cisco1:cisco2
  gather_facts: False
  gather_subset: all

  tasks:
    - name: Get Cisco LLDP Neighbors
      cisco.ios.ios_command:
        commands: show lldp neighbors
      register: lldp_output

    - name: Print output
      ansible.builtin.debug:
        var: lldp_output

    - name: Extract stdout_lines[0]
      ansible.builtin.set_fact:
        lldp:  " {{ lldp_output['stdout_lines'][0] }}"

    - name: Extract LLDP entry
      ansible.builtin.set_fact:
        lldp_entry: "{{ item }}"
      loop: "{{ lldp  }}"
      when: "'twb-sf-hpsw1' in item"

    - name: Set LLDP variables from the .split() output
      ansible.builtin.set_fact:
        remote_device: "{{ lldp_entry.split()[0] }}"
        local_intf: "{{ lldp_entry.split()[1] }}"
        remote_intf: "{{ lldp_entry.split()[-1] }}"

    - name: Display results
      ansible.builtin.debug:
        msg: 
          - "Remote device: {{ remote_device }}"
          - "Local intf: {{ local_intf }}"
          - "Remote intf: {{ remote_intf }}"
