---
- name: Exercise4
  hosts: nxos
  gather_facts: true

  tasks:
    - name: Deploy NXOS Config
      cisco.nxos.nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Verify BGP
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: output

    - name: Show BGP
      ansible.builtin.debug:
        var: output.stdout_lines[0]
