---
- name: NX-OS Playbook
  gather_facts: False
  gather_subset: all
  hosts: nxos

  tasks:
    - name: Get show version
      cisco.nxos.nxos_command:
        commands: 
          - show version
          - show lldp neighbors

      register: show_output

    - ansible.builtin.debug:
        var: show_output["stdout_lines"][1]
