---
- name: Exercise 1d
  hosts: arista5
  gather_facts: True
  gather_subset: all
  vars_files: my_vars.yml

  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print net_all_ipv4_addresses
      ansible.builtin.debug:
        var: ansible_facts.net_all_ipv4_addresses

    - name: Print ansible_network_os
      ansible.builtin.debug:
        var: ansible_network_os

    - name: Print ansible_host
      ansible.builtin.debug:
        var: ansible_host

    - name: Print desired_eos_version
      ansible.builtin.debug:
        var: desired_eos_version
