---
- name: Exercise 1e
  hosts: arista5
  gather_facts: True
  gather_subset: all
  vars_files: my_vars.yml

  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print net_all_ipv4_addresses
      ansible.builtin.debug:
        var: ansible_facts.net_all_ipv4_addresses

    - name: Print ansible_network_os
      ansible.builtin.debug:
        var: ansible_network_os

    - name: Print ansible_host
      ansible.builtin.debug:
        var: ansible_host

    - name: Print desired_eos_version
      ansible.builtin.debug:
        var: desired_eos_version

    - name: Create new variable called device_hostname
      ansible.builtin.set_fact:
        device_hostname: "{{ inventory_hostname }}.lab.io"

    - name: Print new device_hostname variable
      ansible.builtin.debug:
        var: device_hostname
