---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - ios_facts:
      tags: fact_only

    - debug:
        var: ansible_net_model

    - ios_command:
        commands: show ip int brief
