---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - ios_command:
        commands: show ip int brief
      register: output

    - debug:
        #var: output["stdout_lines"]
        # var: output["stdout_lines"][0]
        var: output["stdout_lines"][0][1]
