---
- name: Exercise3a
  hosts: cisco
  gather_facts: true

  tasks:
    - name: Create access-list
      cisco.ios.ios_config:
        before: no ip access-list extended TEST-ANSIBLE1
        parents: ip access-list extended TEST-ANSIBLE1
        lines:
          - permit ip host 10.1.1.1 any
          - permit ip host 10.1.1.2 any
          - permit ip host 10.1.1.3 any
          - permit ip host 10.1.1.4 any
          - permit ip host 10.1.1.5 any
          - permit ip host 10.1.1.6 any
          - permit ip host 10.1.1.7 any
          - permit ip host 10.1.1.8 any
          - permit ip host 10.1.1.9 any
          - permit ip host 10.1.1.10 any

        match: exact
        replace: block

    - name: Verify ACL Configured
      cisco.ios.ios_command:
        commands: show access-list TEST-ANSIBLE1

      register: output

    - name: Display ACL
      ansible.builtin.debug:
        var: output.stdout_lines[0]
