---
- name: Exercise1c
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include tags
      ansible.builtin.include_tasks: subtask2.yml

    - name: Include always tags
      ansible.builtin.include_tasks: subtask2.yml
      tags: always

    - name: Include always tags - p2
      ansible.builtin.include_tasks: subtask2.yml
      tags:
        - mp1
        - mp2
        - mp3
