---
- name: Exercise1a
  hosts: localhost
  gather_facts: False
  
  tasks:
    - name: Include example
      ansible.builtin.include_tasks: subtask1.yml
      loop:
        - 10.10.10.1
        - 10.10.10.2
        - 10.10.10.3
        - 10.10.10.4

